# Generated by Django 5.1.1 on 2024-10-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='following',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='prevent_self_follow'),
        ),
    ]
